spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/loganalyzer
    driver-class-name: org.postgresql.Driver
    username: loganalyzer
    password: loganalyzer

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false

  kafka:
    bootstrap-servers: localhost:9094
    admin:
      fail-fast: false
    consumer:
      group-id: log-analyzer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.arssedot.loganalyzer.web.dto"
        spring.json.value.default.type: "com.arssedot.loganalyzer.web.dto.LogIngestRequest"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
