CREATE TABLE log_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    level VARCHAR(10) NOT NULL,
    service_name VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    trace_id VARCHAR(64),
    host VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_logs_timestamp ON log_entries (timestamp);
CREATE INDEX idx_logs_level ON log_entries (level);
CREATE INDEX idx_logs_service ON log_entries (service_name);
CREATE INDEX idx_logs_created_at ON log_entries (created_at);
