CREATE TABLE dashboard_pages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name         VARCHAR(100) NOT NULL,
    service_name VARCHAR(100),
    position     INT NOT NULL DEFAULT 0,
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_dashboard_pages_user_id ON dashboard_pages(user_id);

ALTER TABLE widgets ADD COLUMN page_id BIGINT REFERENCES dashboard_pages(id) ON DELETE CASCADE;

-- Create a default page for every existing user and reassign their widgets to it
INSERT INTO dashboard_pages (user_id, name, service_name, position)
SELECT id, 'Default', NULL, 0 FROM users;

UPDATE widgets w
SET page_id = (
    SELECT dp.id FROM dashboard_pages dp WHERE dp.user_id = w.user_id LIMIT 1
);
